<a href="https://colab.research.google.com/github/Soumya120/ML/blob/main/Heartdisease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/heart_desease_data.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [ ]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
x= df.iloc[:, [1,2,3,4,6,7]].values
y= df.iloc[:, [13]]

In [ ]:
x

array([[  1,   3, 145, 233,   0, 150],
       [  1,   2, 130, 250,   1, 187],
       [  0,   1, 130, 204,   0, 172],
       ...,
       [  1,   0, 144, 193,   1, 141],
       [  1,   0, 130, 131,   1, 115],
       [  0,   1, 130, 236,   0, 174]])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lg = LogisticRegression(max_iter = 300)

In [ ]:
x_test

array([[  1,   0, 145, 174,   1, 125],
       [  1,   3, 170, 227,   0, 155],
       [  1,   3, 170, 288,   0, 159],
       [  1,   0, 125, 258,   0, 141],
       [  1,   2, 130, 231,   1, 146],
       [  1,   0, 124, 274,   0, 166],
       [  1,   0, 110, 167,   0, 114],
       [  1,   0, 130, 254,   0, 147],
       [  0,   0, 200, 288,   0, 133],
       [  1,   0, 130, 330,   0, 132],
       [  1,   2, 150, 126,   1, 173],
       [  0,   0, 130, 269,   1, 163],
       [  1,   0, 135, 254,   0, 127],
       [  1,   1, 130, 266,   1, 171],
       [  0,   2, 120, 219,   1, 158],
       [  1,   2, 100, 222,   1, 143],
       [  1,   0, 108, 233,   1, 147],
       [  1,   2, 124, 255,   1, 175],
       [  1,   0, 120, 267,   1,  99],
       [  1,   2, 120, 240,   1, 194],
       [  1,   0, 140, 226,   1, 178],
       [  1,   0, 118, 219,   1, 140],
       [  1,   1, 120, 281,   0, 103],
       [  1,   0, 110, 206,   0, 108],
       [  1,   1, 110, 235,   1, 153],
       [  0,   2, 130, 26

In [ ]:
s = lg.fit(x,y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred = lg.predict(x_test)

In [ ]:
lg.score(x,y)

0.7920792079207921

In [ ]:
from sklearn import metrics

In [ ]:
metrics.accuracy_score(y_test, y_pred)

0.819672131147541

In [ ]:
from sklearn.svm import SVC

In [ ]:
model = SVC(gamma = 'auto')

In [ ]:
model.fit(x,y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
model.predict(x_test)

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1])

In [ ]:
model.predict([[60,3,250,300,0,150]])

array([1])

In [ ]:
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score

In [ ]:
loocv = LeaveOneOut()

In [ ]:
results = cross_val_score(model, x,y, cv=loocv)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

In [ ]:
print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0)) 

Accuracy: 53.465% (49.880%)


In [ ]:
scoring = 'roc_auc'

In [ ]:
results = cross_val_score(model, x, y, cv=loocv)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

In [ ]:
print("AUC: %.3f (%.3f)" % (results.mean(), results.std()))

AUC: 0.535 (0.499)


In [ ]:
model.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
predicted = model.predict(x_test)

In [ ]:
matrix = confusion_matrix( y_test, predicted)

In [ ]:
print(matrix)

[[ 1 26]
 [ 1 33]]


In [ ]:
from sklearn.metrics import classification_report

In [ ]:
report = classification_report(y_test, predicted)

In [ ]:
print(report)

              precision    recall  f1-score   support

           0       0.50      0.04      0.07        27
           1       0.56      0.97      0.71        34

    accuracy                           0.56        61
   macro avg       0.53      0.50      0.39        61
weighted avg       0.53      0.56      0.43        61



In [ ]:
scoring = 'neg_mean_absolute_error' 

In [ ]:
results = cross_val_score(model, x, y, cv=loocv) 

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

In [ ]:
print("MAE: %.3f (%.3f)" % (results.mean(), results.std())) 

MAE: -0.465 (0.499)


In [ ]:
print("R^2: %.3f (%.3f)" % (results.mean(), results.std()))

R^2: -0.465 (0.499)


In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
model = GaussianNB()

In [ ]:
result = cross_val_score(model,x,y,cv=loocv)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = col

In [ ]:
print(result.mean())

0.7656765676567657


In [ ]:
from sklearn.linear_model import Lasso

In [ ]:
model = Lasso()

In [ ]:
model.fit(x,y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [ ]:
print(result.mean())

0.7656765676567657


In [ ]:
model.score(x,y)

0.17739286889077632