<a href="https://colab.research.google.com/github/Soumya120/ML/blob/main/Popularity_of_music_artist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('artists.csv')
df.head()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (2,4,6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


mbid              artist_mb  \
0  cc197bad-dc9c-440d-a5b5-d52ba2e14234               Coldplay   
1  a74b1b7f-71a5-4011-9441-d0b5e4122711              Radiohead   
2  8bfac288-ccc5-448d-9573-c33ea2aa5c30  Red Hot Chili Peppers   
3  73e5e69d-3554-40d8-8516-00cb38737a1c                Rihanna   
4  b95ce3ff-3d05-4e87-9e01-c97b66af13d4                 Eminem   

           artist_lastfm      country_mb           country_lastfm  \
0               Coldplay  United Kingdom           United Kingdom   
1              Radiohead  United Kingdom           United Kingdom   
2  Red Hot Chili Peppers   United States            United States   
3                Rihanna   United States  Barbados; United States   
4                 Eminem   United States            United States   

                                             tags_mb  \
0  rock; pop; alternative rock; british; uk; brit...   
1  rock; electronic; alternative rock; british; g...   
2  rock; alternative rock; 80s; 90s; rap; metal; ...   
3  pop; dance; hip hop; reggae; contemporary r b;...   
4  turkish; rap; american; hip-hop; hip hop; hiph...   

                                         tags_lastfm  listeners_lastfm  \
0  rock; alternative; britpop; alternative rock; ...         5381567.0   
1  alternative; alternative rock; rock; indie; el...         4732528.0   
2  rock; alternative rock; alternative; Funk Rock...         4620835.0   
3  pop; rnb; female vocalists; dance; Hip-Hop; Ri...         4558193.0   
4  rap; Hip-Hop; Eminem; hip hop; pop; american; ...         4517997.0   

   scrobbles_lastfm  ambiguous_artist  
0       360111850.0             False  
1       499548797.0             False  
2       293784041.0             False  
3       199248986.0             False  
4       199507511.0             False

In [ ]:
df.isnull().sum()

mbid                      0
artist_mb                 8
artist_lastfm        479327
country_mb           803715
country_lastfm      1254585
tags_mb             1346137
tags_lastfm         1085008
listeners_lastfm     479323
scrobbles_lastfm     479323
ambiguous_artist          0
dtype: int64

In [ ]:
df.drop(['country_mb', 'country_lastfm', 'tags_mb', 'tags_lastfm', 'ambiguous_artist'], axis=1, inplace=True)

In [ ]:
df['popular_or_not'] = df.listeners_lastfm > np.mean(df['listeners_lastfm'])
df['popular_or_not'] = df['popular_or_not'].astype(int)
df

mbid              artist_mb  \
0        cc197bad-dc9c-440d-a5b5-d52ba2e14234               Coldplay   
1        a74b1b7f-71a5-4011-9441-d0b5e4122711              Radiohead   
2        8bfac288-ccc5-448d-9573-c33ea2aa5c30  Red Hot Chili Peppers   
3        73e5e69d-3554-40d8-8516-00cb38737a1c                Rihanna   
4        b95ce3ff-3d05-4e87-9e01-c97b66af13d4                 Eminem   
...                                       ...                    ...   
1466078  1eab523e-98ff-4083-aa34-8922740bc696                    정은지   
1466079  a18f0527-907e-42b0-8268-504966274581                    남태현   
1466080  20a57e37-24b5-4301-855b-35076580fb88                    헤일로   
1466081  83891a4d-1bf4-4abe-a483-5b3d9d614efa                    서현진   
1466082  3d05dd13-f524-4e80-91aa-24094e8b5928                    김희철   

                 artist_lastfm  listeners_lastfm  scrobbles_lastfm  \
0                     Coldplay         5381567.0       360111850.0   
1                    Radiohead         4732528.0       499548797.0   
2        Red Hot Chili Peppers         4620835.0       293784041.0   
3                      Rihanna         4558193.0       199248986.0   
4                       Eminem         4517997.0       199507511.0   
...                        ...               ...               ...   
1466078                    NaN               NaN               NaN   
1466079                    NaN               NaN               NaN   
1466080                    NaN               NaN               NaN   
1466081                    NaN               NaN               NaN   
1466082                    NaN               NaN               NaN   

         popular_or_not  
0                     1  
1                     1  
2                     1  
3                     1  
4                     1  
...                 ...  
1466078               0  
1466079               0  
1466080               0  
1466081               0  
1466082               0  

[1466083 rows x 6 columns]

In [ ]:
lg = LogisticRegression(max_iter=1000)

In [ ]:
df = df.replace([np.inf, -np.inf], np.nan)
df.dropna(how="any", inplace=True)

In [ ]:
x= df.iloc[:, [3,4]].values
y= df.iloc[:, [5]]

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3, random_state=0)

In [ ]:
x

array([[5.38156700e+06, 3.60111850e+08],
       [4.73252800e+06, 4.99548797e+08],
       [4.62083500e+06, 2.93784041e+08],
       ...,
       [0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00]])

In [ ]:
k = lg.fit(x,y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [ ]:
y_pred = lg.predict(x_test)

In [ ]:
lg.score(x,y)

1.0

In [ ]:
y_pred_new = lg.predict([[1594561,84646]])

In [ ]:
print(y_pred_new)

[1]


In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
d= DecisionTreeClassifier()

In [ ]:
d.fit(x,y)

DecisionTreeClassifier()

In [ ]:
y_pred1 = d.predict(x_test)

In [ ]:
y_pred1

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
d.score(x,y)

1.0

In [ ]:
from sklearn.ensemble import RandomForestClassifier 

In [ ]:
r= RandomForestClassifier(n_estimators=1)

In [ ]:
r.fit(x,y)

C:\Users\ADMIN\AppData\Local\Temp/ipykernel_8136/2591809438.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  r.fit(x,y)


RandomForestClassifier(n_estimators=1)

In [ ]:
y_pred2 = r.predict(x_test)

In [ ]:
y_pred2

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
r.score(x,y)

0.9999797315032232

In [ ]:
lg.score(x,y)

1.0